{% set name = "schimpy" %}
{% set data = load_setup_py_data() %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ data['version'] }}"

source:
  #git_url: https://github.com/CADWRDeltaModeling/schimpy.git
  path: ..

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - batch_metrics = schimpy.batch_metrics:main
    - clip_dems = schimpy.clip_dems:main
    - contour_smooth = schimpy.contour_smooth:main
    - convert_mesh = schimpy.convert_mesh:main
    - convert_polygons = schimpy.convert_polygons:main
    - convert_linestrings = schimpy.convert_linestrings:main
    - combine_consume = schimpy.combine_consume:main
    - prepare_schism = schimpy.prepare_schism:main
    - create_vgrid_lsc2 = schimpy.create_vgrid_lsc2:main
    - schism_hotstart = schimpy.schism_hotstart:main
    - split_quad = schimpy.split_quad:main
    - model_time = schimpy.model_time:main
    - gen_elev2d = schimpy.gen_elev2D:main
    - small_areas = schimpy.small_areas:main
    - station = schimpy.station:main 
  #skip:           true

requirements:
  build:
    - python
    - setuptools
    - click >=6.0
    - pytest-runner >=5.0
  run:
    - python
    - Click >=7.0
    - geopandas >=0.6
    - netcdf4 >=1.4
    - xarray >=0.15
    - matplotlib >=3.1
    - scipy >=1.4
    - statsmodels >=0.11
    - palettable >=3.3
    - pyyaml >=5.3
  test:
    imports:
      - schimpy
    source_files:
      - tests
    requires:
      - pytest
      - pytest-cov
    commands:
      - (setlocal && cd tests && pytest && endlocal) # [win]
      - (cd tests; pytest) # [unix]

about:
  home: https://github.com/CADWRDeltaModeling/schimpy
  summary: Tools, scripts, templates and data for running SCHISM on the Bay-Delta
  license: "MIT"
  license_file: LICENSE
