{% set name = "schimpy" %}
{% set data = load_setup_py_data() %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ data['version'] }}"

source:
  #git_url: https://github.com/CADWRDeltaModeling/schimpy.git
  path: ..

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
  {% for entry in data['entry_points']['console_scripts'] %}
    - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
  {% endfor %}
  #skip:           true

requirements:
  build:
    - python
    - pip
    - setuptools
    - pytest-runner >=5.0
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}
  test:
    imports:
      - schimpy
    source_files:
      - tests
    requires:
      - pytest
      - pytest-cov
    commands:
      - (setlocal && cd tests && pytest && endlocal) # [win]
      - (cd tests; pytest) # [unix]

about:
  home: https://github.com/CADWRDeltaModeling/schimpy
  summary: Tools, scripts, templates and data for running SCHISM on the Bay-Delta
  license: data['license']
  license_file: LICENSE
