{# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build -#}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject['project'] %}

package:
  name: "{{ project['name']|lower }}"
  version: "{{ load_setup_py_data() }}"  # Dynamically retrieve version using versioneer

source:
  #git_url: https://github.com/CADWRDeltaModeling/schimpy.git
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -vv .
  noarch: python

requirements:
  build:
    - python
    - pip
    - setuptools
    - pyproj
    - pytest-runner >=5.0
  run:
    - python {{ project['requires-python'] }}
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - schimpy
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - (setlocal && cd tests && pytest && endlocal) # [win]
    - (cd tests; pytest) # [unix]

about:
  home: https://github.com/CADWRDeltaModeling/schimpy
  summary: Tools, scripts, templates and data for running SCHISM on the Bay-Delta
  license: MIT
  license_file: LICENSE
