name: "Sphinx: Render docs"

on: 
  push:
    branches: ["main", "master"]
    paths:
      - "docsrc/**"
      - "schimpy/**"
      - "pyproject.toml"
      - ".github/workflows/build_sphinx.yaml"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: docs-${{ github.ref }}   #"pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install schimpy (no deps), then docs extras
          run: |
            python -m pip install --upgrade pip
            pip install -e . --no-deps
            python - <<'PY'
            import tomllib, subprocess, sys, pathlib
            data = tomllib.load(open("pyproject.toml","rb"))  # or: tomllib.loads(pathlib.Path("pyproject.toml").read_bytes())
            pkgs = data["project"]["optional-dependencies"]["doc"]
            subprocess.check_call([sys.executable, "-m", "pip", "install", *pkgs])
            PY
      
      - name: Build API stubs
        working-directory: docsrc
        run: sphinx-apidoc --force -o . ../schimpy -T --templatedir ./_templates

      - name: Clean & Build HTML
        working-directory: docsrc
        run: |
          make clean
          make html

      - name: Publish docs with ghp-import
        run: ghp-import -n -p -f ./docsrc/_build/html

