name: conda-build

on:
  push:
    paths:
      - "conda.recipe/**"
      - ".github/workflows/python-package-conda.yml"
      - "pyproject.toml"
  pull_request:
    paths:
      - "conda.recipe/**"
      - ".github/workflows/python-package-conda.yml"
      - "pyproject.toml"
  workflow_dispatch:

concurrency:
  group: conda-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Export paths based on RUNNER_TEMP (works everywhere)
      - name: Set temp-based paths
        run: |
          echo "MAMBA_ROOT_PREFIX=${RUNNER_TEMP}/mamba" >> "$GITHUB_ENV"
          echo "CONDA_BLD_PATH=${RUNNER_TEMP}/conda-bld" >> "$GITHUB_ENV"
          echo "PIP_NO_BUILD_ISOLATION=1" >> "$GITHUB_ENV"
          echo "PIP_NO_INDEX=1" >> "$GITHUB_ENV"
          echo "PIP_NO_DEPS=1" >> "$GITHUB_ENV"

      - name: Set up micromamba (with cache)
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: "latest"
          cache-environment: true
          cache-downloads: true
          init-shell: bash
          condarc: |
            channel_priority: strict
            channels:
              - conda-forge
              # add your org channel if your recipe/tests need it:
              # - cadwr-dms

      - name: Create tooling env (cached)
        shell: bash -l {0}
        run: |
          micromamba create -y -n tools \
            python>=3.10 \
            conda-build \
            boa \
            anaconda-client
          micromamba activate tools
          python -V
          conda info

      - name: Build conda recipe (no tests first)
        shell: bash -l {0}
        run: |
          micromamba activate tools
          conda mambabuild conda.recipe --no-test

      - name: Test conda recipe (optional)
        if: always()
        shell: bash -l {0}
        run: |
          micromamba activate tools
          conda mambabuild conda.recipe

      - name: Upload to Anaconda (if token configured)
        if: env.ANACONDA_CHANNEL_UPLOAD_TOKEN != ''
        shell: bash -l {0}
        env:
          ANACONDA_CHANNEL_UPLOAD_TOKEN: ${{ secrets.ANACONDA_CHANNEL_UPLOAD_TOKEN }}
        run: |
          micromamba activate tools
          anaconda -t "$ANACONDA_CHANNEL_UPLOAD_TOKEN" upload --label main "$CONDA_BLD_PATH"/*/*.tar.bz2
